/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'imageData' : IDL.Opt(IDL.Text),
  'isAI' : IDL.Bool,
  'sender' : IDL.Text,
  'timestamp' : Time,
});
export const StudySession = IDL.Record({
  'startTime' : Time,
  'endTime' : Time,
  'user' : IDL.Principal,
  'completed' : IDL.Bool,
  'durationMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
      [],
      [],
    ),
  'createChatSession' : IDL.Func([IDL.Text], [], []),
  'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getStudyHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StudySession)],
      ['query'],
    ),
  'saveStudySession' : IDL.Func([Time, Time, IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'imageData' : IDL.Opt(IDL.Text),
    'isAI' : IDL.Bool,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  const StudySession = IDL.Record({
    'startTime' : Time,
    'endTime' : Time,
    'user' : IDL.Principal,
    'completed' : IDL.Bool,
    'durationMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
        [],
        [],
      ),
    'createChatSession' : IDL.Func([IDL.Text], [], []),
    'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getStudyHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StudySession)],
        ['query'],
      ),
    'saveStudySession' : IDL.Func([Time, Time, IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };